//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testconsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cemasoft.com/", ConfigurationName="ServiceReference1.ObjectSoap")]
    public interface ObjectSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GETCARIKARTLAR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETCARIKARTLAR(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GETCARIKARTLAR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GETCARIKARTLARAsync(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/CARIKARTLARARAMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CARIKARTLARARAMA(string WSPASS, string FILTERSSEARCH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/CARIKARTLARARAMA", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CARIKARTLARARAMAAsync(string WSPASS, string FILTERSSEARCH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENICARIKART", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENICARIKART(string WSPASS, string ConnectionObject, string OBJECTS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENICARIKART", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENICARIKARTAsync(string WSPASS, string ConnectionObject, string OBJECTS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GETSTOKKARTLAR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETSTOKKARTLAR(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GETSTOKKARTLAR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GETSTOKKARTLARAsync(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/STOKKARTIARAMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string STOKKARTIARAMA(string WSPASS, string FILTERSSEARCH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/STOKKARTIARAMA", ReplyAction="*")]
        System.Threading.Tasks.Task<string> STOKKARTIARAMAAsync(string WSPASS, string FILTERSSEARCH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENISTOKKARTI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENISTOKKARTI(string WSPASS, string ConnectionObject, string OBJECTS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENISTOKKARTI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENISTOKKARTIAsync(string WSPASS, string ConnectionObject, string OBJECTS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GETDEPOLAR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETDEPOLAR(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GETDEPOLAR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GETDEPOLARAsync(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATIS_IRSALIYESI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_SATIS_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATIS_IRSALIYESI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_SATIS_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATISTAN_IADE_IRSALIYESI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_SATISTAN_IADE_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATISTAN_IADE_IRSALIYESI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_SATISTAN_IADE_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALIS_IRSALIYESI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_ALIS_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALIS_IRSALIYESI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_ALIS_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALISTAN_IADE_IRSALIYESI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_ALISTAN_IADE_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALISTAN_IADE_IRSALIYESI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_ALISTAN_IADE_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATIS_FATURASI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_SATIS_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATIS_FATURASI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_SATIS_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATISTAN_IADE_FATURASI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_SATISTAN_IADE_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_SATISTAN_IADE_FATURASI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_SATISTAN_IADE_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALIS_FATURASI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_ALIS_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALIS_FATURASI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_ALIS_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALISTAN_IADE_FATURASI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_ALISTAN_IADE_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_ALISTAN_IADE_FATURASI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_ALISTAN_IADE_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_AMBAR_GIRIS_FISI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_AMBAR_GIRIS_FISI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_AMBAR_GIRIS_FISI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_AMBAR_GIRIS_FISIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_AMBAR_CIKIS_FISI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_AMBAR_CIKIS_FISI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_AMBAR_CIKIS_FISI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_AMBAR_CIKIS_FISIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_AMBAR_TRANSFER_FISI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_AMBAR_TRANSFER_FISI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_AMBAR_TRANSFER_FISI", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_AMBAR_TRANSFER_FISIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GET_KASALAR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GET_KASALAR(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/GET_KASALAR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GET_KASALARAsync(string WSPASS, string FILTERS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_TAHSILAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENI_TAHSILAT(string WSPASS, string ConnectionObject, string TAHSILAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENI_TAHSILAT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENI_TAHSILATAsync(string WSPASS, string ConnectionObject, string TAHSILAT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENIDEKONT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YENIDEKONT(string WSPASS, string ConnectionObject, string Dekont);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cemasoft.com/YENIDEKONT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YENIDEKONTAsync(string WSPASS, string ConnectionObject, string Dekont);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ObjectSoapChannel : testconsole.ServiceReference1.ObjectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectSoapClient : System.ServiceModel.ClientBase<testconsole.ServiceReference1.ObjectSoap>, testconsole.ServiceReference1.ObjectSoap {
        
        public ObjectSoapClient() {
        }
        
        public ObjectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GETCARIKARTLAR(string WSPASS, string FILTERS) {
            return base.Channel.GETCARIKARTLAR(WSPASS, FILTERS);
        }
        
        public System.Threading.Tasks.Task<string> GETCARIKARTLARAsync(string WSPASS, string FILTERS) {
            return base.Channel.GETCARIKARTLARAsync(WSPASS, FILTERS);
        }
        
        public string CARIKARTLARARAMA(string WSPASS, string FILTERSSEARCH) {
            return base.Channel.CARIKARTLARARAMA(WSPASS, FILTERSSEARCH);
        }
        
        public System.Threading.Tasks.Task<string> CARIKARTLARARAMAAsync(string WSPASS, string FILTERSSEARCH) {
            return base.Channel.CARIKARTLARARAMAAsync(WSPASS, FILTERSSEARCH);
        }
        
        public string YENICARIKART(string WSPASS, string ConnectionObject, string OBJECTS) {
            return base.Channel.YENICARIKART(WSPASS, ConnectionObject, OBJECTS);
        }
        
        public System.Threading.Tasks.Task<string> YENICARIKARTAsync(string WSPASS, string ConnectionObject, string OBJECTS) {
            return base.Channel.YENICARIKARTAsync(WSPASS, ConnectionObject, OBJECTS);
        }
        
        public string GETSTOKKARTLAR(string WSPASS, string FILTERS) {
            return base.Channel.GETSTOKKARTLAR(WSPASS, FILTERS);
        }
        
        public System.Threading.Tasks.Task<string> GETSTOKKARTLARAsync(string WSPASS, string FILTERS) {
            return base.Channel.GETSTOKKARTLARAsync(WSPASS, FILTERS);
        }
        
        public string STOKKARTIARAMA(string WSPASS, string FILTERSSEARCH) {
            return base.Channel.STOKKARTIARAMA(WSPASS, FILTERSSEARCH);
        }
        
        public System.Threading.Tasks.Task<string> STOKKARTIARAMAAsync(string WSPASS, string FILTERSSEARCH) {
            return base.Channel.STOKKARTIARAMAAsync(WSPASS, FILTERSSEARCH);
        }
        
        public string YENISTOKKARTI(string WSPASS, string ConnectionObject, string OBJECTS) {
            return base.Channel.YENISTOKKARTI(WSPASS, ConnectionObject, OBJECTS);
        }
        
        public System.Threading.Tasks.Task<string> YENISTOKKARTIAsync(string WSPASS, string ConnectionObject, string OBJECTS) {
            return base.Channel.YENISTOKKARTIAsync(WSPASS, ConnectionObject, OBJECTS);
        }
        
        public string GETDEPOLAR(string WSPASS, string FILTERS) {
            return base.Channel.GETDEPOLAR(WSPASS, FILTERS);
        }
        
        public System.Threading.Tasks.Task<string> GETDEPOLARAsync(string WSPASS, string FILTERS) {
            return base.Channel.GETDEPOLARAsync(WSPASS, FILTERS);
        }
        
        public string YENI_SATIS_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATIS_IRSALIYESI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_SATIS_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATIS_IRSALIYESIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_SATISTAN_IADE_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATISTAN_IADE_IRSALIYESI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_SATISTAN_IADE_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATISTAN_IADE_IRSALIYESIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_ALIS_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALIS_IRSALIYESI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_ALIS_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALIS_IRSALIYESIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_ALISTAN_IADE_IRSALIYESI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALISTAN_IADE_IRSALIYESI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_ALISTAN_IADE_IRSALIYESIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALISTAN_IADE_IRSALIYESIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_SATIS_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATIS_FATURASI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_SATIS_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATIS_FATURASIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_SATISTAN_IADE_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATISTAN_IADE_FATURASI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_SATISTAN_IADE_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_SATISTAN_IADE_FATURASIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_ALIS_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALIS_FATURASI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_ALIS_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALIS_FATURASIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_ALISTAN_IADE_FATURASI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALISTAN_IADE_FATURASI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_ALISTAN_IADE_FATURASIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_ALISTAN_IADE_FATURASIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_AMBAR_GIRIS_FISI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_AMBAR_GIRIS_FISI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_AMBAR_GIRIS_FISIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_AMBAR_GIRIS_FISIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_AMBAR_CIKIS_FISI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_AMBAR_CIKIS_FISI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_AMBAR_CIKIS_FISIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_AMBAR_CIKIS_FISIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string YENI_AMBAR_TRANSFER_FISI(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_AMBAR_TRANSFER_FISI(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public System.Threading.Tasks.Task<string> YENI_AMBAR_TRANSFER_FISIAsync(string WSPASS, string ConnectionObject, string USTBILGILER, string KALEMLER) {
            return base.Channel.YENI_AMBAR_TRANSFER_FISIAsync(WSPASS, ConnectionObject, USTBILGILER, KALEMLER);
        }
        
        public string GET_KASALAR(string WSPASS, string FILTERS) {
            return base.Channel.GET_KASALAR(WSPASS, FILTERS);
        }
        
        public System.Threading.Tasks.Task<string> GET_KASALARAsync(string WSPASS, string FILTERS) {
            return base.Channel.GET_KASALARAsync(WSPASS, FILTERS);
        }
        
        public string YENI_TAHSILAT(string WSPASS, string ConnectionObject, string TAHSILAT) {
            return base.Channel.YENI_TAHSILAT(WSPASS, ConnectionObject, TAHSILAT);
        }
        
        public System.Threading.Tasks.Task<string> YENI_TAHSILATAsync(string WSPASS, string ConnectionObject, string TAHSILAT) {
            return base.Channel.YENI_TAHSILATAsync(WSPASS, ConnectionObject, TAHSILAT);
        }
        
        public string YENIDEKONT(string WSPASS, string ConnectionObject, string Dekont) {
            return base.Channel.YENIDEKONT(WSPASS, ConnectionObject, Dekont);
        }
        
        public System.Threading.Tasks.Task<string> YENIDEKONTAsync(string WSPASS, string ConnectionObject, string Dekont) {
            return base.Channel.YENIDEKONTAsync(WSPASS, ConnectionObject, Dekont);
        }
    }
}
